New versions (Aruba.it): HeidiSQL_11.0_64_Portable.zip - httpd-2.4.46-win64-VS16.zip - laragon 4.0.16 190914 (laragon-478753ffe0d02d05003fb075058a1774bc9d4026.zip) - mysql-noinstall-5.0.96-winx64.zip - npp.7.9.portable.x64.7z - php-7.1.33-nts-Win32-VC14-x64.zip - PortableGit-2.29.2-64-bit.7z.exe

diff --git a/bin/git/mingw64/libexec/git-core/git-update-git-for-windows b/bin/git/mingw64/libexec/git-core/git-update-git-for-windows
--- a/bin/git/mingw64/libexec/git-core/git-update-git-for-windows
+++ b/bin/git/mingw64/libexec/git-core/git-update-git-for-windows
@@ -90,6 +90,42 @@ count_other_bashes () {
 	wc -l
 }
 
+# Write HTTP GET response to stdout and return error code. This is equivalent
+# to curl --fail, except that we output the response body to stderr in case of
+# an HTTP error status.
+http_get () {
+	url=$1
+	output=$(mktemp -t gfw-httpget-XXXXXXXX.txt)
+	code=$(curl \
+		--silent \
+		--show-error \
+		--output "$output" \
+		--write-out '%{http_code}' \
+		"$url") || return $?
+	fdout=1
+	ret=0
+	if test "$code" -ge 400
+	then
+		fdout=2
+		ret=22
+	fi
+	cat "$output" >&"$fdout"
+	rm -f "$output"
+	return "$ret"
+}
+
+get_recently_seen() {
+    if [ -f "$HOME"/.git-for-windows-updater ]; then
+        git config -f "$HOME"/.git-for-windows-updater winUpdater.recentlySeenVersion
+    else
+        git config --global winUpdater.recentlySeenVersion
+    fi
+}
+
+set_recently_seen() {
+    git config -f "$HOME"/.git-for-windows-updater winUpdater.recentlySeenVersion "$1"
+}
+
 # The main function of this script
 
 update_git_for_windows () {
@@ -130,7 +166,7 @@ update_git_for_windows () {
 	try_toast=
 	test -z "$use_gui" ||
 	case "$(uname -s)" in
-	*-6.[23]|*-10.0)
+	*-6.[23]|*-6.[23]-[1-9]*|*-10.0|*-10.0-[1-9]*)
 		# Only try to show a Toast notification on Windows 8 & 10,
 		# and only if we have a working wintoast.exe
 		! type wintoast.exe >/dev/null 2>&1 ||
@@ -138,15 +174,15 @@ update_git_for_windows () {
 		;;
 	esac
 
-	releases_url=https://api.github.com/repos/git-for-windows/git/releases
-	releases=$(curl --silent $releases_url/latest) ||
+	latest_tag_url=https://gitforwindows.org/latest-tag.txt
+	latest_tag=$(http_get $latest_tag_url) ||
 	case $?,"$proxy" in
 	7,)
-		proxy="$(proxy-lookup.exe https://api.github.com)" &&
-		test -n "$proxy"
+		proxy="$(proxy-lookup.exe https://gitforwindows.org)" &&
+		test -n "$proxy" &&
 		export https_proxy="$proxy" &&
 		echo "Using proxy $https_proxy as per lookup" >&2 &&
-		releases=$(curl --silent $releases_url/latest) ||
+		latest_tag=$(http_get $latest_tag_url) ||
 		return
 		;;
 	*)
@@ -154,11 +190,9 @@ update_git_for_windows () {
 		;;
 	esac
 
-	latest=$(echo "$releases" |
-		grep '"tag_name": "v' |
-		sed -E 's/.*"tag_name": "v([^"]*).*/\1/')
+	latest=${latest_tag#v}
 	# Did we ask about this version already?
-	recently_seen="$(git config --global winUpdater.recentlySeenVersion)"
+	recently_seen="$(get_recently_seen)"
 	test -n "$quiet" && test "x$recently_seen" = "x$latest" && return
 
 	version=$(git --version | sed "s/git version //")
@@ -166,7 +200,7 @@ update_git_for_windows () {
 	if test -z "$testing" && test "$latest" = "$version"
 	then
 		echo "Up to date" >&2
-		git config --global winUpdater.recentlySeenVersion "$latest"
+		set_recently_seen "$latest"
 		return
 	fi
 	test -n "$testing" ||
@@ -181,6 +215,8 @@ update_git_for_windows () {
 	esac
 
 	echo "Update $latest is available" >&2
+	releases_url=https://api.github.com/repos/git-for-windows/git/releases
+	releases=$(http_get $releases_url/latest) || return
 	download=$(echo "$releases" |
 		grep '"browser_download_url": "' |
 		grep "$bit\-bit\.exe" |
@@ -213,19 +249,17 @@ update_git_for_windows () {
 				;;
 			1|17)
 				# dismiseed, or clicked No: ignore this release
-				git config --global \
-					winUpdater.recentlySeenVersion "$latest"
+				set_recently_seen "$latest"
 				return 1
 				;;
 			4|5|6|9|10)
 				# toast not activated, failed, toasts
 				# unsupported, WinToast init failed or toast
 				# not launched: fall back to using GUI
-				git gui--askyesno \
+				git askyesno \
 					--title "Git Update Available" \
 					"Download and install $name$warn?" || {
-				    git config --global \
-					winUpdater.recentlySeenVersion "$latest"
+				    set_recently_seen "$latest"
 				    return 1
 				}
 				;;
@@ -237,10 +271,9 @@ update_git_for_windows () {
 			esac
 		elif test -n "$use_gui"
 		then
-			git gui--askyesno --title "Git Update Available" \
+			git askyesno --title "Git Update Available" \
 				"Download and install $name$warn?" || {
-				git config --global \
-					winUpdater.recentlySeenVersion "$latest"
+				set_recently_seen "$latest"
 				return 1
 			}
 		else
@@ -249,8 +282,7 @@ update_git_for_windows () {
 			case "$yn" in
 			[Yy]*) ;;
 			*)
-				git config --global \
-					winUpdater.recentlySeenVersion "$latest"
+				set_recently_seen "$latest"
 				return 1;;
 			esac
 		fi
@@ -258,7 +290,7 @@ update_git_for_windows () {
 		echo "Downloading $filename" >&2
 	fi
 	curl -# -L -o $installer $download || return
-	start "" "$installer" /SILENT
+	start "" "$installer" /SILENT /VERYSILENT /NORESTART
 
 	# Kill all Bash processes (which will let MinTTY quit, too)"
 	#
